---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.1.5
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.7.4" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.7.4" STRICT_VARIABLES=yes FUTURE_PARSER=yes
